### ISSUE TITLE
Missing data on the website

### ISSUE THREAD

**Issue by david2vicente** [UXPin/adele#79]
Hello,

Thanks for this website and for merging recent pull requests! 

However i don't see my company (ENGIE) on the website while the PR has been merged (https://github.com/marcintreder/adele/pull/75). Do you have to make a release after that ?

Kind regards

David

**Comment by swistach** [comment]
Hi @david2vicente, we're currently working on the new deploy process and it will be ready soon.
Sorry for that inconvenience. 😞

We'll let you know when your changes will be live on production.

**Comment by david2vicente** [comment]
Hello @swistach , it's actually present on the list now! Thanks :)
