### ISSUE TITLE
Capitalization 

### ISSUE THREAD

**Issue by castastrophe** [UXPin/adele#87]
```suggestion
      "data": "jQuery",
```

^ This is the correct capitalization

_Originally posted by @castastrophe in https://github.com/UXPin/adele/pull/84#discussion_r448436080_

**Comment by castastrophe** [comment]
Adding this as a reminder to myself open aPR for this later. 😁

**Comment by swistach** [comment]
Hi @castastrophe, thank you for catching that 🙂
I'll close this issue, but feel free to open PR with fixes for other mistakes 👍
